configMapGenerator:
- files:
  - application.yml
  name: todo_app-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ceappacr.azurecr.io/todo_app
  newTag: "202410090613"
