apiVersion : apps/v1
kind: Deployment
metadata:
  name: "todoapp-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "todoapp"
  template:
    metadata:
      labels:
        app: "todoapp"
    spec:
      containers:
        - name: "todoapp"
          image: ceappacr.azurecr.io/todo_app
          ports:
          - containerPort: 8080