apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "todoapp-ingress"
spec:
  ingressClassName: ingress-internal
  rules:
  - host: "82023143.ce-aa.kubepia.net"
    http:
      paths:
      - path: /
        backend:
          service:
            name: "todoapp-service"
            port:
              number: 8080
        pathType: Prefix